### ISSUE TITLE
XenoteOS Licensing

### ISSUE THREAD

**Issue by flash76** [LickTheCheese/LickTheCheese.github.io#1]
Hello LTC, I just wanna let you know that licensing has changed on XenoteOS. If you want the latest code, go get it. And read the LICENSE file in the repo

**Comment by LickTheCheese** [comment]
hello, plz put miscellaneous issues in my issues/comments repository instead of randomly puting it here, thx
PS i removed my fork from XenoteOS (because i accidentally forked it and i dont know c#.)

**Comment by icanotc** [comment]
hEloO LtC i just wan u kno u hav speling mistaks iNN uur web sit, pleaze fiks

wen eta
